# Generated by Django 5.2.12 on 2026-03-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0002_remove_result_date_remove_test_time_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Правильный числовой ответ'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('choice', 'Выбор ответа'), ('number', 'Числовой ответ')], default='choice', max_length=10, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Правильный'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
