# Generated by Django 5.2.12 on 2026-03-10 06:10

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0004_remove_answer_correct_remove_question_correct_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пункт основного меню',
                'verbose_name_plural': 'Основное меню',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MathFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название формулы')),
                ('latex_code', models.TextField(verbose_name='LaTeX код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Математическая формула',
                'verbose_name_plural': 'Математические формулы',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок страницы')),
                ('lead', models.TextField(blank=True, verbose_name='Вступительная часть')),
                ('body', ckeditor.fields.RichTextField(blank=True, verbose_name='Основной текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/', verbose_name='Изображение')),
                ('image_caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись к изображению')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Контент страницы',
                'verbose_name_plural': 'Контент страницы',
            },
        ),
        migrations.CreateModel(
            name='SidebarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Текст ссылки')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Ссылка в боковой панели',
                'verbose_name_plural': 'Ссылки в боковой панели',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SideMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('url', models.CharField(max_length=200, verbose_name='Ссылка')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Пункт бокового меню',
                'verbose_name_plural': 'Боковое меню',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testsystem.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='testsystem.test'),
        ),
    ]
