# Generated by Django 5.2.12 on 2026-03-10 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0005_mainmenuitem_mathformula_pagecontent_sidebarlink_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PageContent',
            new_name='SitePage',
        ),
        migrations.AlterModelOptions(
            name='sitepage',
            options={'verbose_name': 'Страница сайта', 'verbose_name_plural': 'Страницы сайта'},
        ),
    ]
