# Generated by Django 5.2.12 on 2026-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0006_rename_pagecontent_sitepage_alter_sitepage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True, verbose_name='URL (slug)'),
        ),
    ]
