# Generated by Django 5.2.12 on 2026-03-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0007_sitepage_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='subject',
            field=models.CharField(blank=True, choices=[('algebra', 'Алгебра'), ('geometry', 'Геометрия'), ('physics', 'Физика')], max_length=20, null=True, verbose_name='Предмет'),
        ),
    ]
