# Generated by Django 5.2.12 on 2026-03-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0008_sitepage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='subject',
            field=models.CharField(choices=[('algebra', 'Алгебра'), ('geometry', 'Геометрия'), ('physics', 'Физика')], default='algebra', max_length=20, verbose_name='Раздел предмета'),
        ),
    ]
