# Generated by Django 5.2.12 on 2026-03-13 05:32

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0009_alter_sitepage_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Основной текст'),
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильно')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testsystem.question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='testsystem.result')),
                ('selected_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testsystem.answer')),
            ],
        ),
    ]
