# Generated by Django 5.2.12 on 2026-03-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0010_alter_sitepage_body_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=10, help_text='Время на тест в минутах'),
        ),
    ]
