# Generated by Django 5.2.12 on 2026-03-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsystem', '0011_test_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='subject',
            field=models.CharField(choices=[('algebra', 'Алгебра'), ('geometry', 'Геометрия'), ('physics', 'Физика')], default='algebra', max_length=20, verbose_name='Предмет'),
        ),
    ]
